org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,27)
neo_version=26.1.2.22-beta
neoforge_full_version=26.1.2.22-beta
neoforge_loader_version=11
neo_version_range=[26.1.2,)
loader_version_range=[11,)

jadeVersion=7938398
jeiVersion=29.5.0.26
jei_mc_version=26.1.2

apothicenchantVersion=26.1.2-4.0.0-beta5
placeboVersion=26.1.2-10.0.0-beta7
attributeslibVersion=26.1.2-3.0.0-beta1

mod_id=beer
mod_name=BEER
mod_license=MIT
mod_version=1.4.2
mod_group_id=com.breakinblocks
mod_authors=TheonlyTazz, BreakingBlocks
mod_description=A small mod that expands the range of Bookshelf detection on the Enchanting Table
