org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.187
neo_version_range=[21,)

jadeVersion=15.10.2
jeiVersion=19.22.1.316
placeboVersion=9.9.0
attributeslibVersion=2.4.0
apothicenchantVersion=1.6.1
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17


mod_id=beer
mod_name=BEER
mod_license=MIT
mod_version=1.4.4
mod_group_id=com.breakinblocks
mod_authors=TheonlyTazz, BreakingBlocks
mod_description=A small mod that expands the range of Bookshelf detection on the Enchanting Table
